FROM python:3.10.11-slim

RUN apt-get update -y && apt-get install -y \
    ffmpeg \
    libsm6 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --upgrade pip setuptools wheel && pip install "setuptools<81"

RUN pip install --no-cache-dir \
    numpy==1.26.4 \
    opencv-python-headless==4.8.1.78 \
    torch==2.5.1 \
    torchvision==0.20.1 \
    torchaudio==2.5.1 \
    --extra-index-url https://download.pytorch.org/whl/cu121 \
    imutils==0.5.4 \
    ultralytics==8.0.145 \
    lapx==0.9.4 \
    kafka-python==2.0.2 \
    tensorboard==2.14.0

COPY . .

CMD ["python", "main.py"]